### ISSUE TITLE
استفاده از کد با رعایت حقوق کدنویس

### ISSUE THREAD

**Issue by m0911** [SCR-IR/jdf.scr.ir#1]
سلام
من می‌خوام کد ویژوال بیسیک شما رو داخل یک فایل اکسس استفاده کنم

تا الان این شکلی کار نکردم و آدابش رو نمی‌دونم
برای این که رفرنس بدم به صفحه کد شما
معمولا چجوری باید نوشت چنین چیزی رو در کامنت برنامه

و اگر بخوام اون فایل اکسس رو داخل گیت هاب بذارم

آیا راهکار خاصی داخل گیت هاب هست که به پیج شما رفرنس بزنه

یا صرفا به صورت کامنت بنویسم لینک و اسم شما رو

با تشکر

**Comment by SCR-IR** [comment]
سلام
همین که یک لینک درج بفرمایید کافیست تا اگر کاربری به منبع احتیاج پیدا کرد، دسترسی آسان داشته‌باشد.
مجوز این کتابخانه‌ها اکثراً
GNU/LGPL
می‌باشد
